# docker run --rm -it -e MTX_PROTOCOLS=tcp -p 8554:8554 -p 1935:1935 -p 8888:8888 -p 8889:8889 aler9/rtsp-simple-server
version: '2'
services:
  rtsp-server:
    image: aler9/rtsp-simple-server
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
    environment:
      MTX_PROTOCOLS: tcp
